# Use an official Node.js runtime as a base image
FROM node:latest

# Update OS mostly to enjoy latest security updates
RUN apt-get update && apt-get upgrade -y

# Set the working directory inside the container
WORKDIR /usr/src

# get data from git repository
RUN git clone https://github.com/handtrixx/dev.niklas-stephan.de.git .

# Copy the rest of the application code to the working directory
RUN chown -R node:node /usr/src
RUN chmod +x /usr/src/utils/startup-prd.sh
RUN chmod +x /usr/src/utils/startup-dev.sh

# update npm package manager if required
RUN npm install -g npm

# set user to node
USER node

# Define the startup command
CMD ["sh","/usr/src/utils/startup-prd.sh"]
#CMD ["tail", "-f", "/dev/null"]

# Add healthcheck
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:3000/ || exit 1